name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.1'
      - uses: golangci/golangci-lint-action@v3
      - run: go version
      - run: make lint

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.1'
      - run: go version
      - run: make test

  cmd-line-arg-parsing-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.1'
      - run: go version
      - run: make build
      - run: ./scripts/test-arg.sh

  cmd-regression-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.1'
      - run: go version
      - run: make build
      - run: ./scripts/test-cmd.sh
